- name: install and run nginx
  hosts: web
  become: yes #root access
  tasks: 
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: latest
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes