- name: variables
  hosts: web
  vars_prompt:
   - name: USERNAME
     prompt: please enter username
   - name: PASSWORD
     prompt: please enter password
  tasks:
  - name: print info
    ansible.builtin.debug:
     msg: "username is {{USERNAME}} and password is {{PASSWORD}}"