- name: to demonstrate conditions in ansible
  hosts: localhost
  tasks:
    - name : To run user command
      ansible.builtin.command: id expense
      register: USER
      ignore_errors: true
    
    - name : To create user if the user doesnt exist
      ansible.builtin.command: useradd expense
      when: USER.rc !=0


  