- name: default value
  hosts: localhost
  vars:
    greeting: "Hello, Good Morning"
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg:"Hello {{Course | default('Ansible')}}"
