- name: default value
  hosts: localhost
  vars:
    greeting: "Hello, Good Morning"
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{Course | default('Ansible')}}"

  - name: print upper case
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"
  
  - name: print lower case
    ansible.builtin.debug:
      msg: "{{greeting | lower}}"

  